apply plugin: 'com.android.application'

android {
    compileSdk 36
    defaultConfig {
        targetSdk 36
        minSdk 23
        vectorDrawables.useSupportLibrary true

        applicationId "com.aes_pl.simple_bluetooth_terminal"
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig true
    }
    namespace 'com.aes_pl.simple_bluetooth_terminal'
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.material
}
